## Lab 3

Step 1 - Load Data

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('spam.csv', encoding='latin-1') # specifying encoding is necessary because the data does not use UTF-8

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

Step 2a - Drop column

In [2]:
# Drop the last 3 columns using iloc
df = df.drop(df.iloc[:,2:], axis=1)

# Check the data
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Step 2b - Inspect Data

In [11]:
# Check the number of instances per class
print(df['Label'].value_counts())
print('\n')

# Check for completeness of data
print(df.info())
print('\n')

# Check descriptive statistics
print(df.describe())

Label
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Label    5572 non-null   str
 1   Message  5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB
None


       Label                 Message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

Step 2c - Label Encoding

In [13]:
# Data for labels
new_labels = {
    'spam': 1,
    'ham': 0
}

# Encode labels
df['Labels'] = df['Label'].map(new_labels)

# Check the data
df.head()

  Label                                            Message  Labels
0   ham  Go until jurong point, crazy.. Available only ...       0
1   ham                      Ok lar... Joking wif u oni...       0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3   ham  U dun say so early hor... U c already then say...       0
4   ham  Nah I don't think he goes to usf, he lives aro...       0

Step 2d - Separate Features and Labels

In [19]:
X = df['Message'].values
y = df['Label'].values

Step 3 - Feature Extraction

In [21]:
X = df['Message'].astype(str)
y = df['Label']

print(type(X), type(y), len(X), len(y))

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=50
)

<class 'pandas.Series'> <class 'pandas.Series'> 5572 5572

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()
X_train = bow.fit_transform(X_train)
X_test = bow.transform(X_test)

print(len(bow.get_feature_names_out()))
print(f'Training data dimensions: {X_train.shape}')
print(f'Test data dimensions: {X_test.shape}')

7727
Training data dimensions: (4457, 7727)
Test data dimensions: (1115, 7727)

Step 4 - Model Training and Evaluation

In [26]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Initialize MultinomialNB
mnb = MultinomialNB()

# Fit the model
mnb.fit(X_train, y_train)

# Predict on the training data
y_pred_train = mnb.predict(X_train)

# Evaluate training accuracy
acc_train = accuracy_score(y_train, y_pred_train)

# Predict on the training data
y_pred_test = mnb.predict(X_test)

# Evaluate training accuracy
acc_test = accuracy_score(y_test, y_pred_test)

# Print evaluation results
print(f'Training data accuracy: {acc_train}')
print(f'Test data accuracy: {acc_test}')

Training data accuracy: 0.9946152120260264
Test data accuracy: 0.9775784753363229